version: 2.1

commands:
  run_package:
    parameters:
      package:
        type: string
    steps:
      # For root, only install dependencies
      - when:
          condition:
            equal:
              - << parameters.package >>
              - root
          steps:
            - restore_cache:
                name: "[root] Restoring cache"
                keys:
                  - npm-{{ .Environment.CACHE_VERSION }}-root-{{ checksum "package-lock.json" }}
            - run:
                name: "[root] Installing dependencies"
                command: |
                  if ! [ -d node_modules ]; then
                    # Cache is not available, install dependencies
                    npm ci
                  fi
            - save_cache:
                name: "[root] Saving cache"
                key: npm-{{ .Environment.CACHE_VERSION }}-root-{{ checksum "package-lock.json" }}
                paths: node_modules
      - unless:
          condition:
            equal:
              - << parameters.package >>
              - root
          steps:
            - restore_cache:
                name: "[<< parameters.package >>] Restoring cache"
                keys:
                  - npm-{{ .Environment.CACHE_VERSION }}-<< parameters.package >>-{{ checksum "./packages/<< parameters.package >>/package-lock.json" }}
            - run:
                name: "[<< parameters.package >>] Installing dependencies"
                working_directory: ./packages/<< parameters.package >>
                command: |
                  if ! [ -d node_modules ]; then
                    echo "Cache is not available, installing dependencies"
                    npm ci
                  else
                    echo "Cache is available, skipping installation"
                  fi
            - save_cache:
                name: "[<< parameters.package >>] Saving cache"
                key: npm-{{ .Environment.CACHE_VERSION }}-<< parameters.package >>-{{ checksum "./packages/<< parameters.package >>/package-lock.json" }}
                paths: ./packages/<< parameters.package >>/node_modules
            - run:
                name: "[<< parameters.package >>] Running tests"
                working_directory: ./packages/<< parameters.package >>
                command: |
                  npm run test:ci --if-present
  install_chromium:
    steps:
      - run:
          name: Installing Chromium
          command: |
            sudo apt-get update
            sudo apt-get install -yq chromium-browser libxss1
  install_concurrently:
    steps:
      - run:
          name: Installing "concurrently"
          command: |
            npm i -g concurrently

jobs:
  test:
    docker:
      - image: 'cimg/node:15.0-browsers'
    steps:
      - checkout
      # - install_chromium
      - install_concurrently
      # - run_package:
      #     package: root
      - run_package:
          package: core
      # - run_package:
      #     package: create-app
      # - run_package:
      #     package: plugin-babel
      # - run_package:
      #     package: plugin-react-refresh
      # - run_package:
      #     package: plugin-sass
      # - run_package:
      #     package: plugin-svelte
      # - run_package:
      #     package: plugin-vue

workflows:
    run_tests:
      jobs:
        - test
