version: 2.1
orbs:
  node: circleci/node@2.0.3
jobs:
  test:
    executor:
      name: node/default
      tag: '14.9.0'
    steps:
      - checkout
      - run:
        name: Install Chromium
        command: |
          sudo apt-get update
          sudo apt-get install -yq chromium-browser
      - node/install-packages
      - run: npx lerna bootstrap
      - run: npm run test
workflows:
    run_tests:
      jobs:
        - test
