version: 2.1
orbs:
  node: circleci/node@2.0.3
  puppeteer: threetreeslight/puppeteer@0.1.2
jobs:
  test:
    executor:
      name: node/default
      tag: '14.9.0'
    steps:
      - checkout
      - run: sudo apt-get update
      - run: sudo apt-get install -yq libgbm
      - puppeteer/install
      - node/install-packages
      - run: npx lerna bootstrap
      - run: npm run test
workflows:
    run_tests:
      jobs:
        - test
