version: 2.1

orbs:
  node: circleci/node@2.0.3

commands:
  install-deps:
    parameters:
      package:
        type: string
    steps:
      when:
        condition:
          equal:
            - << parameters.package >>
            - root
        steps:
          - restore_cache:
              keys:
                - v1-npm-root-{{ checksum "package-lock.json" }}
                - v1-npm-root-
          - run:
              name: Installing dependencies for "root"
              command: npm ci
          - save_cache:
              key: v1-npm-root-{{ checksum "package-lock.json" }}
              paths: node_modules
      unless:
        condition:
          equal:
            - << parameters.package >>
            - root
        steps:
          - restore_cache:
              keys:
                - v1-npm-<< parameters.package >>-{{ checksum "./packages/<< parameters.package >>/package-lock.json" }}
                - v1-npm-<< parameters.package >>-
          - run:
              name: Installing dependencies for "<< parameters.package >>"
              command: npm ci
              working_directory: ./packages/<< parameters.package >>
          - save_cache:
              key: v1-npm-<< parameters.package >>-{{ checksum "./packages/<< parameters.package >>/package-lock.json" }}
              paths: ./packages/<< parameters.package >>/node_modules

jobs:
  test:
    docker:
      - image: 'cimg/node:14.9.0'
    steps:
      - checkout
      - run:
          name: Installing Chromium
          command: |
            sudo apt-get update
            sudo apt-get install -yq chromium-browser
      - install-deps:
          package: root
      - install-deps:
          package: core
      - install-deps:
          package: create-app
      - install-deps:
          package: plugin-babel
      - install-deps:
          package: plugin-react-refresh
      - install-deps:
          package: plugin-sass
      - install-deps:
          package: plugin-svelte
      - install-deps:
          package: plugin-vue
      - run:
          name: Bootstrapping packages
          command: npx lerna bootstrap
      - run:
          name: Running tests
          command: npm run test

workflows:
    run_tests:
      jobs:
        - test
