version: 2.1
orbs:
  puppeteer: threetreeslight/puppeteer@0.1.2
jobs:
  build:
    docker:
      - image: circleci/node:latest-browsers
        environment:
          NODE_ENV: development
  steps:
      - checkout
      - run: npm i lerna
      - run: npx lerna bootstrap
      - run: npm run test
