version: 2.1
orbs:
  node: circleci/node@2.0.3
jobs:
  test:
    docker:
      - image: 'cimg/node:14.9.0'
    steps:
      - checkout
      - run:
          name: Installing Chromium
          command: |
            sudo apt-get update
            sudo apt-get install -yq chromium-browser
      - node/install-packages
      - run:
          name: Bootstrapping packages
          command: npx lerna bootstrap
      - run:
          name: Running tests
          command: npm run test
workflows:
    run_tests:
      jobs:
        - test
