version: 2.1

orbs:
  node: circleci/node@2.0.3

commands:
  run_package:
    parameters:
      package:
        type: string
    steps:
      # For root, only install dependencies
      - when:
          condition:
            equal:
              - << parameters.package >>
              - root
          steps:
            - restore_cache:
                keys:
                  - v1-npm-root-{{ checksum "package-lock.json" }}
            - run:
                name: Installing dependencies for "root"
                command: |
                  if ! [ -d node_modules ]; then
                    # Cache is not available, install dependencies
                    npm ci
                  fi
            - save_cache:
                key: v1-npm-root-{{ checksum "package-lock.json" }}
                paths: node_modules
      - unless:
          condition:
            equal:
              - << parameters.package >>
              - root
          steps:
            - restore_cache:
                keys:
                  - v1-npm-<< parameters.package >>-{{ checksum "./packages/<< parameters.package >>/package-lock.json" }}
            - run:
                name: Installing dependencies for "<< parameters.package >>"
                working_directory: ./packages/<< parameters.package >>
                command: |
                  if ! [ -d node_modules ]; then
                    echo "Cache is not available, installing dependencies"
                    npm ci
                  else
                    echo "Cache is available, skipping installation"
                  fi
            - save_cache:
                key: v1-npm-<< parameters.package >>-{{ checksum "./packages/<< parameters.package >>/package-lock.json" }}
                paths: ./packages/<< parameters.package >>/node_modules
            - run:
                name: Running tests for "<< parameters.package >>"
                command: |
                  npm run test:ci --if-present

jobs:
  test:
    docker:
      - image: 'cimg/node:14.9.0'
    steps:
      - checkout
      - run:
          name: Installing Chromium
          command: |
            sudo apt-get update
            sudo apt-get install -yq chromium-browser
      - run_package:
          package: root
      - run_package:
          package: core
      
      # We don't have test for these packages
      # - run_package:
      #     package: create-app
      # - run_package:
      #     package: plugin-babel
      # - run_package:
      #     package: plugin-react-refresh
      # - run_package:
      #     package: plugin-sass
      # - run_package:
      #     package: plugin-svelte
      # - run_package:
      #     package: plugin-vue

workflows:
    run_tests:
      jobs:
        - test
