version: 2.1
orbs:
  node: circleci/node@2.0.3
jobs:
  test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages
      - run: npx lerna bootstrap
      - run: npm run test
workflows:
    run_tests:
      jobs:
        - test
