name: Tests

on:
  push:
    paths-ignore:
    - 'docs/**'
    - 'playground/**'
    - 'plugin-template/**'
    - '**.md'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: [core]
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: '15.x'
    - name: Install dependencies
      working-directory: ./packages/${{ matrix.package }}
      run: |
        # Workaround for now
        # rm package-lock.json
        npm install
    - name: Run tests
      working-directory: ./packages/${{ matrix.package }}
      env:
        CI: true
      run: npm run test:ci
