name: Tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package-name: [core]
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: '15.x'
    - name: Install dependencies
      run: |
        cd ./packages/${{ matrix.package-name }}
        # Workaround for now
        rm package-lock.json
        npm i
    - name: Run tests
      run: npm run test:ci
      env:
        CI: true
