# I made this workflow because builds on CircleCI were failing
# While making this GitHub Action work, I found what was wrong (package-lock.json was out of sync)
# So currently I am going back to CircleCI
# I will use this Action if CircleCI starts to fail again

# name: Tests

# on:
#   push:
#     paths-ignore:
#     - 'docs/**'
#     - 'playground/**'
#     - 'plugin-template/**'
#     - '**.md'

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     strategy:
#       matrix:
#         package: [core]
#     steps:
#     - uses: actions/checkout@v2

#     - name: Setup Node.js ${{ matrix.node-version }}
#       uses: actions/setup-node@v1
#       with:
#         node-version: '15.x'
    
#     - name: Install dependencies
#       working-directory: ./packages/${{ matrix.package }}
#       run: npm ci
    
#     - name: Run tests
#       working-directory: ./packages/${{ matrix.package }}
#       env:
#         CI: true
#       run: npm run test:ci
