name: Tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package-name: ['core']
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: '15.x'
    - run: cd ./packages/${{ matrix.package-name }}
    - run: npm ci
    - run: npm run test:ci
      env:
        CI: true
